[package]
name = "yxd-auth-kdc"
description = "YXD auth key distribution center (T3P)"
version = "0.0.0"
authors = ["Erik Zscheile <zseri.devel@ytrizja.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
yxd-auth-core = { path = "../core" }
async-channel = "1.5"
serde = "1.0"
toml = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2.4"
