[package]
name = "yxd-server-executor"
version = "0.1.0"
authors = ["Erik Zscheile <zseri.devel@ytrizja.de>"]
edition = "2018"
license = "ISC OR Apache-2.0"

[dependencies]
async-executor = "1.3"
event-listener = "2.5"
futures-lite = "1.11"
num_cpus = "1.13"
